version: "3.8"
services:
  postgres:
    image: "postgres:12.3"
    network_mode: bridge
    container_name: cv
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=cv
      - POSTGRES_DB=db
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data:rw
      - ./scripts:/scripts

volumes:
  cv-data:
